version: '3'

services:
  dependencies:
    build: .
    image: base 
  db:
    container_name: postgres_banner_db
    image: postgres:16.0
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: banner_db
    healthcheck:
      test: "pg_isready --username=postgres && psql --username=postgres --list"
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 5s

  banner: 
    container_name: avito_banner
    build: 
      context: ./cmd/banner/
      dockerfile: dockerfile
    volumes:
      - ./logs:/app/logs
    ports:
      - "8090:8090"
    depends_on:
      db:
        condition: service_healthy
      dependencies:
        condition: service_started
